### ISSUE TITLE
No right click on function

### ISSUE THREAD

**Issue by pahlers** [anvaka/jsruntime#1]
Nice tool and nice work. I want to use it. But I don't have the right click (http://youtu.be/x91YVWQsw2g?t=22s) on a function (see my screenshot). Furthermore I don't have any errors.

![Screen Shot 2013-02-19 at 8 14 27 ](https://f.cloud.github.com/assets/432408/170363/b3ba7c5c-7a64-11e2-8e2f-3113e707b612.png)

**Comment by anvaka** [comment]
I assume it's because `CSSPrimitiveValue` is not a function, but a number. Right click works on functions only.

**Comment by pahlers** [comment]
I see that right. The right click only works on non-native functions. Thanks!
