### ISSUE TITLE
Invoke it

### ISSUE THREAD

**Issue by fr33wi11** [anvaka/jsruntime#2]
Hi, 

How to invoke it? I dont see any button, link etc under chrome version 39
???

Thanks

**Comment by anvaka** [comment]
It should be in the "Elements" panel, in the same split where "Styles/Computed/Event Listeners/...":

![demo](http://i.imgur.com/TdGL5Jv.png)

**Comment by vrobik** [comment]
Sorry for comment, but maybe it can help some on like me who not close DevTools before installing extension, JS Runtime tab appear after reopening DevTools in this case.

**Comment by anvaka** [comment]
@vrobik thank you for the tip!

I've updated readme file with concrete instructions. Please check this out: https://github.com/anvaka/jsruntime

**Comment by nahongyan** [comment]
Hello, I saw your demo video on YouTube, can you tell me how you got that tweetclick? And I don't have that column here either. It's Chrome 87
